#ifndef CARL_CONSTANTS
#define CARL_CONSTANTS

enum LexerError {
    UNTERMINATED_STRING = 10,
    INCOMPLETE_DELIMITER = 11,
    UNRECOGNIZED_CHARACTER = 12,
};

enum ParserError {
    UNEXPECTED_TOKEN = 100,
    MISSING_CLOSING_BRACKET = 101,
};

#endif
