#ifndef CARL_CONSTANTS
#define CARL_CONSTANTS

enum LexerError {
    UNTERMINATED_STRING = 10,
    INCOMPLETE_DELIMITER = 11,
    UNRECOGNIZED_CHARACTER = 12,
};

enum ParserError {
    SYNTAX_ERROR = 100,
    UNEXPECTED_TOKEN = 101,
    MISSING_CLOSING_BRACKET = 102,
    MISSING_TERMINATOR = 103,
};

enum RuntimeError {
    TYPE_MISMATCH = 1000,
};

#endif
